### ISSUE TITLE
manual installation with qutebrowser

### ISSUE THREAD

**Issue by nicodebo** [alphapapa/solarized-everything-css#33]
hi,

This looks like a nice project.
I want to try it but I'm wondering how to load a css file with qutebrowser.

**Comment by The-Compiler** [comment]
This really isn't the right place for qutebrowser support, but you want the [content.user_stylesheets](qute://help/settings.html#content.user_stylesheets) setting.

**Comment by nicodebo** [comment]
sorry for the inconveniance. And many thanks for the hint.
