### ISSUE TITLE
Need exclusion mechanism in build system for all-sites sheets

### ISSUE THREAD

**Issue by non-Jedi** [alphapapa/solarized-everything-css#37]
Using qutebrowser with solarized-dark-all-sites.css, reddit looks like this:

![solarized-reddit-weird](https://user-images.githubusercontent.com/17915621/37481497-4e273e8c-2858-11e8-886a-38551a91b4fe.png)

I'm not great with web-stuff, so it's very possible this is just something I've somehow screwed up myself. Can anyone else reproduce?

**Comment by The-Compiler** [comment]
Huh, that sure is weird! I can't reproduce FWIW.

**Comment by non-Jedi** [comment]
Ah. It's specific to the multi-theme branch. Just checked out master, and everything works fine. Can anyone reproduce on multi-theme?

**Comment by alphapapa** [comment]
In general, the `all-sites.css` files are not guaranteed nor even expected to work well.  They are a mashup of all the sites' stylesheets into one file.  When possible you should use site-specific files, and if problems arise then, file a bug against specific stylesheets.

**Comment by non-Jedi** [comment]
Looks like qutebrowser 1.2 is out now, so that's now actually actionable. @alphapapa should I close as wontfix?

**Comment by jgkamat** [comment]
@non-Jedi by the way, I remove the bigblow stylesheet (since it seems to be the main offender to the all-sites working well). Without the bigblow stylesheet, it works great for me on all the sites that I frequent (and I personally keep it that way for simplicity).

The reason that this is an issue on multi-theme is that the bigblow stylesheet was removed on master (and re-added on multi-theme).

**Comment by alphapapa** [comment]
I guess what we need is a modification to the build script to exclude certain styles from the all-sites file.  I hesitate to add the extra configuration and complexity, but if it really does make the difference between that file being useful or not, it seems like the right thing to do.

@non-Jedi I think I will repurpose this issue for that idea.  No promises as to when it may be implemented, but at least you have a workaround until then.  :)
