### ISSUE TITLE
Wikipedia dark has some issues

### ISSUE THREAD

**Issue by amno1** [alphapapa/solarized-everything-css#54]
[Wikipedia start page](https://imgur.com/a/xQ0EGVQ)

Two elements on Wikipedia start page are left without solarized style. Also the popup list when one types search term is left unstyled. Probably not a big deal since the front page is not used that often, but maybe of interest anyway.

**Comment by alphapapa** [comment]
Thanks.  Sites like this change their CSS so often that it's virtually impossible to keep up.  I never look at the Wikipedia front page, anyway.

**Comment by amno1** [comment]
To be honest I don't look at Wikipedia front page neither. It happened just because I Emacs threw me there by misstake. Anyway I looked more at it, seems like it was clash between solarized-everywhere and youtube-solarized scripts. For some reason greasemonkey decided to run both YT-everywhere and S-everywhere on Wikipedias page. After disabling YT-everywhere it works fine.
