### ISSUE TITLE
Light variant not working

### ISSUE THREAD

**Issue by matejdro** [alphapapa/solarized-everything-css#62]
Not sure if something is up with my install process or a script is buggy. This is basically what I did:

1. Open https://userstyles.org/styles/127328/solarized-everything-github
2. Select Customize Settings
3. Set Variant to Light
4. Click Install
5. Refresh Github
6. Github was DARK instead of Light

This is with Firefox and Stylus extension.

**Comment by alphapapa** [comment]
GitHub's CSS churns too frequently to keep up with in the way this project works.  I gave up trying long ago.  You might try one of the other CSS-styling projects that replaces colors in GitHub's CSS, etc.

Having said that, patches welcome, but I'm not doing it myself anymore.
